<a href="https://colab.research.google.com/github/vir92/learning_pytorch/blob/main/Learn_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.6.0+cu124


# **Introduction to tensors**

In [2]:
#creating tensors
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3,6],[3,6,9,8],[2,4,5,8]]])
TENSOR

tensor([[[1, 2, 3, 6],
         [3, 6, 9, 8],
         [2, 4, 5, 8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 4])

In [15]:
TENSOR[0]

tensor([[1, 2, 3, 6],
        [3, 6, 9, 8],
        [2, 4, 5, 8]])

### Random Tensors

why random tensors?
Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data .

'start with random numbers->look at data ->update random numbers->look at data ->update random numbers'


Torch random tensors https://docs.pytorch.org/docs/2.7/generated/torch.rand.html


In [22]:
### Random tensors
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.5623, 0.7678, 0.7465, 0.2678],
        [0.9222, 0.5354, 0.8772, 0.9995],
        [0.5123, 0.1409, 0.1562, 0.0698]])

In [23]:
random_tensor.ndim

2

In [25]:
 #create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) #height , width , color channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###Zeros and ones

In [26]:
#create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

###Creating a rannge of tensors-like

In [35]:
#use torch.range()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes